# Generated by Django 3.2.6 on 2021-09-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('B', 'صبحانه'), ('D', 'نوشیدنی'), ('DI', 'شام'), ('L', 'نهار')], default='D', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
