# Generated by Django 3.2.6 on 2021-09-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_food_type_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('Breakfast', 'صبحانه'), ('Drinks', 'نوشیدنی'), ('Dinner', 'شام'), ('Lunch', 'نهار')], default='Drinks', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
