# Generated by Django 3.2.6 on 2021-10-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_food_type_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='food',
            name='time',
        ),
        migrations.AlterField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('Breakfast', 'صبحانه'), ('food', 'غذا'), ('drinks', 'نوشیدنی')], default='drinks', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
