# Generated by Django 3.2.6 on 2021-10-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_auto_20211011_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(max_length=100, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('Breakfast', 'صبحانه'), ('food', 'غذا'), ('dessert', 'دسر')], default='drinks', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
