# Generated by Django 3.2.6 on 2021-10-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس الکترونیکی')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('message', models.CharField(max_length=400, verbose_name='پیغام')),
            ],
        ),
    ]
