# Generated by Django 3.2.6 on 2021-10-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Realte',
            new_name='Relate',
        ),
    ]
