# Generated by Django 3.2.6 on 2021-10-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211008_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descriptions',
            field=models.CharField(max_length=200, verbose_name='توضیحات'),
        ),
    ]
